/*
 * CheckInGUI.java
 * 
 * Version Information Final
 *
 * Date 04/12/2017

 * @author Adam Graham, x16339141
 *
 */
package flightapp;

/**
 *
 * @author adam
*
 */
import flightapp.FirstClass;
import flightapp.Flight;
import flightapp.Receipt;
import javax.swing.*;

public class CheckInGUI extends javax.swing.JFrame {
/* variables later to be called created */
    int seat1;
    private Flight f;
    String s1 = "";
    
    /**
     * Creating all buttons, labels and boxes for GUI
     */
    public CheckInGUI() {
        initComponents();
        jLabel1.setVisible(false);
        luggageDd.setVisible(false);
        luggageLbl.setVisible(false);
        nameFld.setVisible(false);
        nameLbl.setVisible(false);
        passportFld.setVisible(false);
        passportLbl.setVisible(false);
        seatBtn.setVisible(false);
        seatFld.setVisible(false);
        checkinBtn.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refLbl = new javax.swing.JLabel();
        refFld = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        nameFld = new javax.swing.JTextField();
        luggageLbl = new javax.swing.JLabel();
        luggageDd = new javax.swing.JComboBox<>();
        passportLbl = new javax.swing.JLabel();
        passportFld = new javax.swing.JTextField();
        checkInLbl = new javax.swing.JLabel();
        seatBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        seatFld = new javax.swing.JLabel();
        checkinBtn = new javax.swing.JButton();
        contBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refLbl.setText("Reference Number:");

        refFld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refFldActionPerformed(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLbl.setText("Name:");

        nameFld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        luggageLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        luggageLbl.setText("Luggage:");

        luggageDd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        luggageDd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Bag", "2 Bags", "3 Bags", "4 Bags" }));
        luggageDd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luggageDdActionPerformed(evt);
            }
        });

        passportLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passportLbl.setText("Passport Number:");

        passportFld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passportFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportFldActionPerformed(evt);
            }
        });

        checkInLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkInLbl.setForeground(new java.awt.Color(7, 7, 112));
        checkInLbl.setText("Check In");

        seatBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seatBtn.setText("Generate Seat Number");
        seatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seatBtnMouseEntered(evt);
            }
        });
        seatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        seatFld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seatFld.setText("Seat No:");

        checkinBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkinBtn.setText("Check in!");
        checkinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinBtnActionPerformed(evt);
            }
        });

        contBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contBtn.setText("Continue");
        contBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refLbl)
                            .addComponent(passportLbl)
                            .addComponent(luggageLbl))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refFld)
                            .addComponent(passportFld)
                            .addComponent(nameFld)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(luggageDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkInLbl)
                            .addComponent(checkinBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatFld, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(contBtn)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(checkInLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contBtn))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passportLbl)
                    .addComponent(passportFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(luggageLbl)
                    .addComponent(luggageDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatFld, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(checkinBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luggageDdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luggageDdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luggageDdActionPerformed
/*creating a random number generator for the seat number */
    private void seatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatBtnActionPerformed
        seatFld.setText(s1 = "");
        seat1 = 1 + (int) (Math.random() * 200);

        s1 += seat1;
        seatFld.setText(s1);


    }//GEN-LAST:event_seatBtnActionPerformed

    private void seatBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatBtnMouseEntered

    }//GEN-LAST:event_seatBtnMouseEntered

    private void refFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refFldActionPerformed
/* creating actions to be preformed when checkin button is clicked, eg displaying receipt */
    private void checkinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinBtnActionPerformed
    
            
        Receipt r = new Receipt();
        r.setVisible(true);
        
        r.setFlight(f);
        
        if(f instanceof FirstClass){
           f.setRefNum(refFld.getText());
            f.setPassNum(Integer.parseInt(passportFld.getText()));
            f.setPassName(nameFld.getText());
            f.setLuggage(String.valueOf(luggageDd.getSelectedItem()));
            f.setSeatNum(Integer.parseInt(seatFld.getText()));
    }
            
        
        
        
        
         
        
    }//GEN-LAST:event_checkinBtnActionPerformed
/* telling programme what to do in each case of entering a refernece number into the application */
    private void contBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contBtnActionPerformed

        String refNum = "0928379LHR";

        if (refNum.equals(refFld.getText())) {
            JOptionPane.showConfirmDialog(null, "You are flying to Heathrow?", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
            jLabel1.setVisible(true);
            luggageDd.setVisible(true);
            luggageLbl.setVisible(true);
            nameFld.setVisible(true);
            nameLbl.setVisible(true);
            passportFld.setVisible(true);
            passportLbl.setVisible(true);
            seatBtn.setVisible(true);
            seatFld.setVisible(true);
            checkinBtn.setVisible(true);
            
        }
        
        refNum = "0928379AMS";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "Are you flying to Amseterdam?", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        refNum = "0928379FRA";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are fying to Frankfurt", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        refNum = "0928379MUC";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Munich", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        refNum = "0928379CDG";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to CHarles De Gaul", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        refNum = "0928379IST";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Istanbul", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        
        refNum = "0928379GTW";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Gatwick", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        
        refNum = "0928379CPH";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Copenhagen", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        
        refNum = "0928379BCN";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Barcelona", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        
        refNum = "0928379VIH";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Vienna", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        
        refNum = "0928379ORY";
        
        if (refNum.equals(refFld.getText())) {
                JOptionPane.showMessageDialog(null, "You are flying to Paris", "Flight Path...", JOptionPane.INFORMATION_MESSAGE);
                jLabel1.setVisible(true);
                luggageDd.setVisible(true);
                luggageLbl.setVisible(true);
                nameFld.setVisible(true);
                nameLbl.setVisible(true);
                passportFld.setVisible(true);
                passportLbl.setVisible(true);
                seatBtn.setVisible(true);
                seatFld.setVisible(true);
                checkinBtn.setVisible(true);
        }
        
        else if(refNum != refFld.getText()){
            JOptionPane.showMessageDialog(null, "Invalid Reference number, please try again");
        }
        
        
        
        

    }//GEN-LAST:event_contBtnActionPerformed

    private void passportFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckInGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkInLbl;
    private javax.swing.JButton checkinBtn;
    private javax.swing.JButton contBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> luggageDd;
    private javax.swing.JLabel luggageLbl;
    private javax.swing.JTextField nameFld;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField passportFld;
    private javax.swing.JLabel passportLbl;
    private javax.swing.JTextField refFld;
    private javax.swing.JLabel refLbl;
    private javax.swing.JButton seatBtn;
    private javax.swing.JLabel seatFld;
    // End of variables declaration//GEN-END:variables
}
