/*
 * PaymentGUI.java
 * 
 * Version Information Final
 *
 * Date 04/12/2017

 * @author YuZhang Chen, x16336066
 *
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard
 */
public class PaymentGUI extends javax.swing.JFrame  {

    Flight f; //Creating a instance of the super class 
    Payment p = new Payment(); //Creating a instance of payment 
    private ArrayList<Payment> pays;//Declare ArrayList of type Payment
    int size;// counter
    int error; //error counter 
    
    public void setFlight(Flight f){ //sending over the arraylist from the TicketsGUI
        this.f=f;
    }

    public PaymentGUI() {
        initComponents();
        cBox.setVisible(false);
        cHNameFld.setVisible(false); //hiding the components 
        cardnoFld.setVisible(false);
        cvcFld.setVisible(false);
        expiryFld.setVisible(false);
        cHNameLbl.setVisible(false);
        cardnoLbl.setVisible(false);
        cvcLbl.setVisible(false);
        emailLbl.setVisible(false);
        emailFld.setVisible(false);
        tCLbl.setVisible(false);
        costLbl.setVisible(false);
        expiryLbl.setVisible(false);
        submitBtn.setVisible(false);
        pays = new ArrayList<>();//create ArrayList called pays 
        readFromFile(); // starting the readfromfile method 
        size = 0; //setting the size and error counter to 0
        error = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        refLbl = new javax.swing.JLabel();
        refFld = new javax.swing.JTextField();
        cardnoLbl = new javax.swing.JLabel();
        cardnoFld = new javax.swing.JTextField();
        cvcLbl = new javax.swing.JLabel();
        cvcFld = new javax.swing.JTextField();
        expiryLbl = new javax.swing.JLabel();
        expiryFld = new javax.swing.JTextField();
        cHNameLbl = new javax.swing.JLabel();
        cHNameFld = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailFld = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cBox = new javax.swing.JCheckBox();
        tCLbl = new javax.swing.JLabel();
        proceedBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        costLbl = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Enter your credit card number:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Ticket Payment ");

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo.png"))); // NOI18N
        logoLbl.setText("jLabel2");

        refLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        refLbl.setText("Enter your booking referance no:");

        refFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refFldActionPerformed(evt);
            }
        });

        cardnoLbl.setFont(cardnoLbl.getFont().deriveFont((float)24));
        cardnoLbl.setText("Enter your credit card number:");

        cardnoFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnoFldActionPerformed(evt);
            }
        });

        cvcLbl.setFont(cvcLbl.getFont().deriveFont(cvcLbl.getFont().getSize()+8f));
        cvcLbl.setText("CVC:");

        cvcFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvcFldActionPerformed(evt);
            }
        });

        expiryLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        expiryLbl.setText("Expiry date:");

        expiryFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryFldActionPerformed(evt);
            }
        });

        cHNameLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cHNameLbl.setText("Cardholder's name:");

        cHNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHNameFldActionPerformed(evt);
            }
        });

        emailLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emailLbl.setText("Email:");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cBox.setText("I authorise Ryanair to deduct the above from my account");
        cBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxActionPerformed(evt);
            }
        });

        tCLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tCLbl.setText("Total cost: €");

        proceedBtn.setText("Proceed to payment ");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        adminBtn.setText("Admin");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Records ");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refLbl)
                        .addGap(45, 45, 45)
                        .addComponent(refFld, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proceedBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cardnoFld, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cvcLbl)
                        .addGap(15, 15, 15)
                        .addComponent(cvcFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(expiryLbl)
                        .addGap(15, 15, 15)
                        .addComponent(expiryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cHNameLbl)
                        .addGap(15, 15, 15)
                        .addComponent(cHNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLbl)
                        .addGap(15, 15, 15)
                        .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tCLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(costLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cBox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminBtn)
                        .addGap(9, 9, 9)
                        .addComponent(deleteBtn)
                        .addGap(254, 254, 254)
                        .addComponent(submitBtn))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(refFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(proceedBtn)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cardnoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvcLbl)
                    .addComponent(expiryLbl)
                    .addComponent(cHNameLbl)
                    .addComponent(cHNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cvcFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiryFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCLbl)
                    .addComponent(costLbl))
                .addGap(12, 12, 12)
                .addComponent(cBox)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminBtn)
                    .addComponent(deleteBtn)
                    .addComponent(submitBtn)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refFldActionPerformed

    private void cardnoFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnoFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnoFldActionPerformed

    private void cvcFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvcFldActionPerformed

    private void expiryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryFldActionPerformed

    private void cHNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cHNameFldActionPerformed

    private void cBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxActionPerformed

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // TODO add your handling code here:
        
        String ref = f.getRefNum(); //getting the ref number from the ticketsgui
        String userRef=refFld.getText(); //grabbing the referance number the user entered 
        if (ref.equals(userRef)) { // checking the user entered aginst the one stored in the TicketsGUI
        cBox.setVisible(true); //settiung all the elements to visible 
        cHNameFld.setVisible(true);
        cardnoFld.setVisible(true);
        cvcFld.setVisible(true);
        expiryFld.setVisible(true);
        cHNameLbl.setVisible(true);
        cardnoLbl.setVisible(true);
        cvcLbl.setVisible(true);
        emailLbl.setVisible(true);
        emailFld.setVisible(true);
        tCLbl.setVisible(true);
        costLbl.setVisible(true);
        expiryLbl.setVisible(true);
        submitBtn.setVisible(true); 
       double cost = f.getIncVat(); //gettiung the total cost and storing it in the veriable called cost 
       String tc = Double.toString(cost); // changing the double to a string 
       costLbl.setText(tc); // displaying the cost 
       p.setRefNum(ref); // adding to the arraylist p
       p.setIncVat(cost);
        }
        else{
            JOptionPane.showMessageDialog(null, "Incorrect referance number."); // error message 
        }
        
        
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here
        int cardNo = Integer.parseInt(cardnoFld.getText());   //grabbing from textfield 
        int cvc = Integer.parseInt(cvcFld.getText());
        int expiry = Integer.parseInt(expiryFld.getText());    
        int cvcLength = (int) (Math.floor(Math.log10(cvc) + 1)); // checking how many digits are in the number the user entered 
        int expiryLength = (int) (Math.floor(Math.log10(expiry) + 1));
        String email = emailFld.getText();

        if (cBox.isSelected()) { //making sure the checkbox is slected before anything is done 
            p.setCardNo(cardNo); // adding cardno to the arraylist 

            if (cvcLength == 3) { //checking if the cvc number is 3 digits 
                p.setCvc(cvc); //adding the cvc to the arraylist 
            } else {
                error++; //increase the error count if cvc is not 3 digits 
                JOptionPane.showMessageDialog(null, "The CVC number you have entered is incorrect."); //error message 
            }

            if (expiryLength == 4) { //checking if the expiry date is 4 digits 
                p.setExpiry(expiry); //setting the expiry date 
            } else {
                error++; //increasing the error count 
                JOptionPane.showMessageDialog(null, "The expiry date you have entered is incorrect."); //error message 
            }
            p.setEmail(email); //adding email and card holder name to the array list 
            p.setcHName(cHNameFld.getText()); 
            if (error == 0) { //making sure the error counnt is 0 before storeing the arraylist and writting to file 
                pays.add(p);
                writeToFile();
                CheckInGUI check = new CheckInGUI();
                check.setVisible(true);
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please make sure you have authorized Ryan Air to deduct the total from your card."); // error message 
        }

        error = 0; // reseting the error count 
    }//GEN-LAST:event_submitBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        int pass = Integer.parseInt(JOptionPane.showInputDialog(null, "Password:")); //asking the user for password before displaying the information 
        if (pass == 1234) {
            for (Payment p : pays) { //for loop to loop through the arraylist 
                JOptionPane.showMessageDialog(null,"Reference Number:"+p.getRefNum()+ "\n Card Number:" + p.getCardNo() + "\n  CVC:" + p.getCvc() + "\n  Expiry Date:" + p.getExpiry() + "\n  Card holder's name:" + p.getcHName() + "\n  Email:" + p.getEmail()+"\n Ampount Paid"+p.getIncVat()); //displaying the information 
            }
        } else { 
            JOptionPane.showMessageDialog(null, "Password incorrect."); //error message 
        }
    }//GEN-LAST:event_adminBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int pass = Integer.parseInt(JOptionPane.showInputDialog(null, "Password:")); //asking for password before deleting the arraylist 
        if (pass == 1234) {
            pays.clear();
        } else {
            JOptionPane.showMessageDialog(null, "Password incorrect.");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed
    public void writeToFile() {  //write to file method 
        try {
            File f = new File("payment.txt");
            FileOutputStream fStream = new FileOutputStream(f);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(pays);
            oStream.close();
            JOptionPane.showMessageDialog(null, "Payment Successful");
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    public void readFromFile() { //read from file method 
        try {
            File f = new File("payment.txt");
            FileInputStream fStream = new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(fStream);
            pays = (ArrayList<Payment>) oStream.readObject();
            oStream.close();
            JOptionPane.showMessageDialog(null, "Read From File Successful");
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PaymentGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JCheckBox cBox;
    private javax.swing.JTextField cHNameFld;
    private javax.swing.JLabel cHNameLbl;
    private javax.swing.JTextField cardnoFld;
    private javax.swing.JLabel cardnoLbl;
    private javax.swing.JLabel costLbl;
    private javax.swing.JTextField cvcFld;
    private javax.swing.JLabel cvcLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailFld;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField expiryFld;
    private javax.swing.JLabel expiryLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JTextField refFld;
    private javax.swing.JLabel refLbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel tCLbl;
    // End of variables declaration//GEN-END:variables
}
